source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'webrick'
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.4'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'rack-flash3'
gem 'dotenv'
gem 'mutex_m'
gem 'bigdecimal'

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner'
end
